config/routes.rb
Rails.application.routes.draw do
  resources :products

  resources :uesertypes

  resources :uesrtypes

  resources :users

  devise_for :users, :skip => [:registrations, :sessions]

  as :user do
    get "/login" => "devise/sessions#new", :as => :new_user_session
    post "/login" => "devise/sessions#create", :as => :user_session
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end
	root :to => 'home#index'
end

app/controllers/uesertypes_controller.rb
class UesertypesController < ApplicationController
  before_action :set_uesertype, only: [:show, :edit, :update, :destroy]

  # GET /uesertypes
  # GET /uesertypes.json
  def index
    @uesertypes = Uesertype.all
  end

  # GET /uesertypes/1
  # GET /uesertypes/1.json
  def show
  end

  # GET /uesertypes/new
  def new
    @uesertype = Uesertype.new
  end

  # GET /uesertypes/1/edit
  def edit
  end

  # POST /uesertypes
  # POST /uesertypes.json
  def create
    @uesertype = Uesertype.new(uesertype_params)

    respond_to do |format|
      if @uesertype.save
        format.html { redirect_to @uesertype, notice: 'Uesertype was successfully created.' }
        format.json { render :show, status: :created, location: @uesertype }
      else
        format.html { render :new }
        format.json { render json: @uesertype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /uesertypes/1
  # PATCH/PUT /uesertypes/1.json
  def update
    respond_to do |format|
      if @uesertype.update(uesertype_params)
        format.html { redirect_to @uesertype, notice: 'Uesertype was successfully updated.' }
        format.json { render :show, status: :ok, location: @uesertype }
      else
        format.html { render :edit }
        format.json { render json: @uesertype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uesertypes/1
  # DELETE /uesertypes/1.json
  def destroy
    @uesertype.destroy
    respond_to do |format|
      format.html { redirect_to uesertypes_url, notice: 'Uesertype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uesertype
      @uesertype = Uesertype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def uesertype_params
      params.require(:uesertype).permit(:name, :description)
    end
end

app/helpers/uesertypes_helper.rb
module UesertypesHelper
end

app/views/uesertypes/_form.html.erb
<%= form_for(@uesertype) do |f| %>
  <% if @uesertype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uesertype.errors.count, "error") %> prohibited this uesertype from being saved:</h2>

      <ul>
      <% @uesertype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uesertypes/edit.html.erb
<h1>Editing Uesertype</h1>

<%= render 'form' %>

<%= link_to 'Show', @uesertype %> |
<%= link_to 'Back', uesertypes_path %>

app/views/uesertypes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Uesertypes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uesertypes.each do |uesertype| %>
      <tr>
        <td><%= uesertype.name %></td>
        <td><%= uesertype.description %></td>
        <td><%= link_to 'Show', uesertype %></td>
        <td><%= link_to 'Edit', edit_uesertype_path(uesertype) %></td>
        <td><%= link_to 'Destroy', uesertype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Uesertype', new_uesertype_path %>

app/views/uesertypes/new.html.erb
<h1>New Uesertype</h1>

<%= render 'form' %>

<%= link_to 'Back', uesertypes_path %>

app/views/uesertypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @uesertype.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @uesertype.description %>
</p>

<%= link_to 'Edit', edit_uesertype_path(@uesertype) %> |
<%= link_to 'Back', uesertypes_path %>